/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as TrashIndexRouteImport } from './routes/trash/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashIndexRoute = TrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/settings': typeof SettingsRoute
  '/home/': typeof HomeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/trash/': typeof TrashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/settings': typeof SettingsRoute
  '/home': typeof HomeIndexRoute
  '/library': typeof LibraryIndexRoute
  '/trash': typeof TrashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/settings': typeof SettingsRoute
  '/home/': typeof HomeIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/trash/': typeof TrashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/settings' | '/home/' | '/library/' | '/trash/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/settings' | '/home' | '/library' | '/trash'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/settings'
    | '/home/'
    | '/library/'
    | '/trash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  SettingsRoute: typeof SettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  TrashIndexRoute: typeof TrashIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash/': {
      id: '/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof TrashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  SettingsRoute: SettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  TrashIndexRoute: TrashIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
